DROP TABLE IF EXISTS WORKOUT;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS TRAINER;

-- Создание таблицы CLIENT
CREATE TABLE IF NOT EXISTS CLIENT (
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
birthday DATE NOT NULL,
telephone VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
login VARCHAR(50) NOT NULL
);

--Создание таблицы TRAINER
CREATE TABLE IF NOT EXISTS TRAINER (
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
birthday DATE NOT NULL,
telephone VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
login VARCHAR(50) NOT NULL
);

--Создание таблицы WORKOUT
CREATE TABLE IF NOT EXISTS WORKOUT (
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
client_id INTEGER NOT NULL,
trainer_id INTEGER NOT NULL,
start_time DATETIME NOT NULL,
end_time DATETIME NOT NULL,
FOREIGN KEY (client_id) REFERENCES CLIENT(id) ON DELETE CASCADE,
FOREIGN KEY (trainer_id) REFERENCES TRAINER(id) ON DELETE CASCADE
)