DROP TABLE IF EXISTS WORKOUT;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS TRAINER;

-- Создание таблицы CLIENT
CREATE TABLE IF NOT EXISTS CLIENT (
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
birthday DATE NOT NULL,
telephone VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
login VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL
);

--Создание таблицы TRAINER
CREATE TABLE IF NOT EXISTS TRAINER (
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
birthday DATE NOT NULL,
telephone VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
login VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL
);

--Создание таблицы WORKOUT
CREATE TABLE IF NOT EXISTS WORKOUT (
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
client_id INTEGER NOT NULL,
trainer_id INTEGER NOT NULL,
"date" DATE NOT NULL,
start_time TIME NOT NULL,
end_time TIME NOT NULL,
FOREIGN KEY (client_id) REFERENCES CLIENT(id) ON DELETE CASCADE,
FOREIGN KEY (trainer_id) REFERENCES TRAINER(id) ON DELETE CASCADE,
CONSTRAINT unique_trainer_date_time UNIQUE (trainer_id, "date", start_time),
CONSTRAINT unique_client_date_time UNIQUE (client_id, "date", start_time)
);


